InstantCommand Intake
chopshop-166/frc-2020 pull request #16
Opened 2020-01-25 18:37 UTC by DavidDesfosse

2020-01-25 18:38 UTC, msoucy commented
This is actually Tyler's pull request, but David was signed in to GitKraken

2020-01-25 18:47 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Intake.java
> +//The intake takes in the balls from the ground, stores them and relays that number, then it puts them into the shooter(if ball goes into storage area, then it adds that number to a storage system)
I think we want the intake subsystem to only cover the mechanism that flips down out of the robot and intakes the power cells.

The rest of this behavior should be included in the `indexer` subsystem.

2020-01-31 23:40 UTC, bot190 requested changes

2020-01-31 23:40 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Intake.java
> +    // Infrared Proximity Sensor
This seems misplaced. Please remove this.

2020-01-31 23:40 UTC, bot190 commented on src/main/java/frc/robot/Robot.java
> +        copilotController.getButton(Button.kBumperRight).whenHeld(intake.deployPiston());
Instead of mapping these two commands we should map the command group we created. Talk to Mason about what button he wants to use

2020-01-31 23:40 UTC, bot190 commented on src/main/java/frc/robot/maps/RobotMap.java
> +import edu.wpi.first.wpilibj2.command.InstantCommand;
This should be removed.

2020-01-31 23:40 UTC, bot190 commented on src/main/java/frc/robot/maps/RobotMap.java
> +    public static class IndexMap {
`IndexMap` changes should not be in the Intake pull request.

2020-01-31 23:40 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Intake.java
> + * by pneumatic pistons There is only one speed for the intake motor(Member:
Fix punctuation in this paragraph

2020-01-31 23:40 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Intake.java
> +    public CommandBase placeRoller() {
Still not a fan of this function name. Can we come up with something better?

2020-02-01 02:25 UTC, msoucy requested changes
Very close, just needs a couple of tweaks.

2020-02-01 02:25 UTC, msoucy commented on src/main/java/frc/robot/Robot.java
> +    final private Indexer indexer = new Indexer(map.getIndexMap());
Remove this line, it should be added as part of the Indexer PR

2020-02-01 02:25 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Intake.java
> +        return runRoller();
Kind of like how `deployPiston` and `retractPiston` use the same function with different arguments, make `runRoller` take a speed argument and pass different values in from `intake` and `discharge`. Right now both commands run the motors in the same direction.

2020-02-05 00:36 UTC, msoucy requested changes
Just a couple of nitpicks for cleanup, otherwise looks good!

2020-02-05 00:36 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Intake.java
> +    // pneumatic pistons to raise the intake up so that balls can get underneath
Comment isn't really "attached" to anything - it would make sense to go with the members, or remove it.

2020-02-05 00:36 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Intake.java
> +    private static final double intakeMotorSpeed = 0.85;
Constants are generally named with `SCREAMING_SNAKE_CASE`. Please change.

2020-02-05 00:54 UTC, bot190 submitted a review, later dismissed
Looks good!

2020-02-05 00:54 UTC, msoucy submitted a review, later dismissed
Fix the travis issues, then it looks good

2020-02-05 01:06 UTC, msoucy approved these changes
:shipit:

2020-02-05 01:07 UTC, merged