Documentation
chopshop-166/frc-2020 pull request #17
Opened 2020-01-25 18:53 UTC by jeffaburke

2020-01-25 19:49 UTC, msoucy requested changes

2020-01-25 19:49 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> + * 6) Sensors? Speed Controllers
These aren't sensors

2020-01-25 19:49 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> + * 6) Sensors? Speed Controllers
Are there encoders? Gyros?

2020-01-25 19:49 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> + * 2) What modes does it have? Has a mode to differentiate between right and
This is not a mode - those are just members.

2020-01-25 19:49 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> + * 4) How is it triggered -> OI? Triggered by motors to make the robots wheels
Triggered **by** motors?

2020-02-01 00:01 UTC, bot190 requested changes

2020-02-01 00:01 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Drive.java
> +     * @param turn    defines the direction to turn
These don't really "define" the directions, they provide the amount of forward/turning speed.

2020-02-01 00:01 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Drive.java
> +    public CommandBase driveFlip(DoubleSupplier forward, DoubleSupplier turn) {
This should have the same comment structure as the `drive` command. 

It should also be bound to a button with `toggleWhenActive`.

2020-02-05 01:20 UTC, bot190 requested changes
A few comments to cleanup the `driveFlip` command

2020-02-05 01:20 UTC, bot190 commented on src/main/java/frc/robot/maps/TempestMap.java
> +    public IntakeMap getIntakeMap() {
This shouldn't be here.

2020-02-05 01:20 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Drive.java
> +            double yAxis = forward.getAsDouble();
This should really just be providing a new DoubleSupplier to `drive` that reverses the direction.

2020-02-07 21:55 UTC, bot190 requested changes
A few more changes.

2020-02-07 21:55 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Intake.java
> +    }
This change shouldn't be here.

2020-02-07 21:55 UTC, bot190 commented on src/main/java/frc/robot/subsystems/Drive.java
> +     * Defines the left and right motor(s) and then puts them into a differential
This doesn't `Define` motors, it gets them from the robot map. Please update this comment.

2020-02-07 21:55 UTC, bot190 commented on src/main/java/frc/robot/maps/RobotMap.java
> +        return null;
This seems dangerous. We should provide a mock drive map, probably in ChopShopLib. For now this should provide mock speed controllers

2020-02-07 23:22 UTC, msoucy requested changes

2020-02-07 23:22 UTC, msoucy commented on src/main/java/frc/robot/maps/HyperionMap.java
> +<<<<<<< HEAD
This doesn't seem like it's in the right place...

2020-02-07 23:22 UTC, msoucy commented on src/main/java/frc/robot/maps/TempestMap.java
> +<<<<<<< HEAD
Merge conflict

2020-02-07 23:22 UTC, msoucy commented on src/main/java/frc/robot/maps/TempestMap.java
> +<<<<<<< HEAD
Merge conflict

2020-02-07 23:22 UTC, msoucy commented on src/main/java/frc/robot/maps/TempestMap.java
> +<<<<<<< HEAD
Merge conflict

2020-02-07 23:22 UTC, msoucy commented on src/main/java/frc/robot/maps/TempestMap.java
> +<<<<<<< HEAD
Merge conflict

2020-02-07 23:22 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Intake.java
> +    }
Please undo this

2020-02-08 00:43 UTC, bot190 approved these changes

2020-02-08 00:45 UTC, msoucy requested changes

2020-02-08 00:45 UTC, msoucy commented on src/main/java/frc/robot/maps/HyperionMap.java
> +    public DifferentialDriveMap getDriveMap() {
This should be `@Override`

2020-02-08 00:45 UTC, msoucy commented on src/main/java/frc/robot/maps/HyperionMap.java
> +    public DifferentialDriveMap getDriveMap() {
Does this chassis have a gyro?

2020-02-08 00:45 UTC, msoucy commented on src/main/java/frc/robot/maps/TempestMap.java
> +    public DifferentialDriveMap getDriveMap() {
Does this chassis have a gyro?

2020-02-08 01:40 UTC, msoucy approved these changes

2020-02-08 01:40 UTC, merged