Added Francois Map
chopshop-166/frc-2020 pull request #20
Opened 2020-02-11 23:52 UTC by jeffaburke

2020-02-12 03:46 UTC, bot190 requested changes
This is a good start. We'll need to update it once we get some of the other subsystems merged.

2020-02-12 03:46 UTC, bot190 commented on src/main/java/frc/robot/maps/FrancoisMap.java
> +@RobotMapFor("Tempest")
This should be updated.

2020-02-13 00:23 UTC, msoucy approved these changes
LGTM :shipit:

2020-02-13 00:26 UTC, bot190 approved these changes

2020-02-13 00:26 UTC, merged