Added Current Limits to TalonSRXs
chopshop-166/frc-2020 pull request #48
Opened 2020-02-27 00:21 UTC by andrewmartin5

all except for intake

2020-02-27 05:14 UTC, bot190 reviewed
Just a few small changes, and we'll definitely want to test these values to make sure they aren't problematic.

2020-02-27 05:14 UTC, bot190 commented on src/main/java/frc/robot/maps/FrancoisMap.java
> +import frc.robot.subsystems.ControlPanel;
This seems misplaced, please remove.

2020-02-27 05:14 UTC, bot190 commented on src/main/java/frc/robot/maps/RobotMap.java
> +    public void BAGCurrentLimit(TalonSRX talon) {
May want to call this `setBagCurrentLimits`

2020-02-28 05:50 UTC, bot190 requested changes
A few more requests, sorry. I just want to make sure this doesn't impact us during normal play while still providing some safety.

2020-02-28 05:50 UTC, bot190 commented on src/main/java/frc/robot/maps/RobotMap.java
> +        talon.configPeakCurrentLimit(15, 0);
Lets make this 25 for now

2020-02-28 05:50 UTC, bot190 commented on src/main/java/frc/robot/maps/RobotMap.java
> +        talon.configContinuousCurrentLimit(10, 0);
Probably increase this to 15.

2020-03-12 01:00 UTC, msoucy commented
@andrewmartin5 can you merge master into this, fix the conflicts, and push?

2021-01-29 01:51 UTC, msoucy commented
This PR could use some TLC. And a rebase. :)

2021-02-26 23:02 UTC, bot190 approved these changes

2021-02-26 23:02 UTC, merged