Add initial Java parser for PathPlanner
chopshop-166/frc-2020 pull request #61
Opened 2021-03-24 00:21 UTC by bot190

Defined basic functions and objects to prepare for trajectoryAdds a utility class that can parse a PathPlanner CSV into a Trajectory.

2021-03-30 01:20 UTC, msoucy requested changes

2021-03-30 01:20 UTC, msoucy commented on src/main/java/frc/robot/Robot.java
> +                drive.autonomousCommand("Bounce1", true, false).andThen(drive.autonomousCommand("Bounce2", true, false))
One thing I noticed is that `x.andThen(y).andThen(z).andThen(q)` can just be done as `x.andThen(y, z, q)` and will produce a more "flat" command structure.

2021-03-30 01:20 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Drive.java
> +        if (isJson) {
Do we plan on sticking with just JSON or just CSV, or supporting both long term?

2021-03-30 01:20 UTC, msoucy commented on src/main/java/frc/robot/utils/PathPlannerUtils.java
> +        y = 4.572 - lineSplit[4];
Magic number?

2021-03-30 01:20 UTC, msoucy commented on src/main/java/frc/robot/utils/PathPlannerUtils.java
> +        state.curvatureRadPerMeter = 1 / lineSplit[6];
This scared me for a moment. Would you mind doing `1.0 / lineSplit[6]` just so it's more obvious that it's floating-point division?

2021-03-30 01:20 UTC, msoucy commented on src/main/java/frc/robot/utils/PathPlannerUtils.java
> +        state.poseMeters = pose;
Why does this use a temporary variable?

2021-03-30 01:20 UTC, msoucy commented on src/main/java/frc/robot/utils/PathPlannerUtils.java
> +    public static Trajectory fromPathPlannerCSV(Path path) throws IOException {
Can has documentation? (Here and elsewhere)

Basically if it's going to go in chopshoplib someday it should have documentation early

2021-04-06 23:27 UTC, msoucy commented
Status? Rebase?

2021-04-06 23:51 UTC, bot190 commented
The only part of this we might keep is `PathPlannerUtils.java` which should go to chopshoplib. Closing this.

2021-04-06 23:51 UTC, closed without merging