Dpad mapped to toggle shooter and intake
chopshop-166/frc-2020 pull request #62
Opened 2021-04-01 22:44 UTC by andrewmartin5

Dpad Up: Shooter on slow speed
Dpad Down: Shooter off
Dpad Left: Deploy Intake
Dpad RIght: Retract Intake

2021-04-01 23:19 UTC, bot190 approved these changes, later dismissed

2021-04-01 23:29 UTC, msoucy requested changes

2021-04-01 23:29 UTC, msoucy commented on src/main/java/frc/robot/Robot.java
> +        final DpadTrigger stopShooter = DpadTrigger.DpadDown(driveController);
Why make the triggers just to use them once in the next line? Combine them please

2021-04-01 23:29 UTC, msoucy commented on src/main/java/frc/robot/triggers/DpadTrigger.java
> +    public DpadTrigger(XboxController controller, int angle) {
Can all these angles just be a nice enum or similar, instead of having tons of nearly identical functions?

2021-04-01 23:29 UTC, msoucy commented on src/main/java/frc/robot/subsystems/Shooter.java
> +    public CommandBase SlowSpin() {
Why is that capitalized?

2021-04-02 02:18 UTC, msoucy commented
This needs a rebase

2021-04-03 13:45 UTC, bot190 approved these changes

2021-04-03 14:25 UTC, msoucy approved these changes

2021-04-03 14:25 UTC, merged